# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5JOU8hluWaggiOdXVh8q4U8JQsA16TJ
"""

temDentes = 'sim'
temFome = 'não'
gosta = 'sim'

if temDentes == 'sim' :
    TDcondicao = 'verdadeiro'
elif temDentes == 'não':
    TDcondicao = 'falso'
if temFome == 'sim' :
    TFcondicao = 'verdadeiro'
elif temFome == 'não' :
    TFcondicao = 'falso'
if gosta == 'sim' :
    Gcondicao = 'verdadeiro'
elif gosta == 'não' :
    Gcondicao = 'falso'

if Gcondicao == 'falso' or TFcondicao == 'falso':
    GTFcondicao = 'falso'
else:
    GTFcondicao = 'verdadeiro'

if GTFcondicao == 'verdadeiro' and TDcondicao == 'verdadeiro' :
    Fcondicao = 'verdadeiro'
else:
    Fcondicao = 'verdadeiro'
print(f'Apessoa precisa ter dentes {TDcondicao} e ter fome {TFcondicao} ou gostar de maçã {Gcondicao}')